apiVersion: v1
kind: Service
metadata:
  name: {{ include "sourcebot.fullname" . }}
  labels:
    {{- include "sourcebot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sourcebot.selectorLabels" . | nindent 4 }}
---
{{- if .Values.oauth2Proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sourcebot.oauth2ProxyFullname" . }}
  labels:
    {{- include "sourcebot.oauth2ProxyLabels" . | nindent 4 }}
spec:
  type: {{ .Values.oauth2Proxy.service.type }}
  ports:
    - port: {{ .Values.oauth2Proxy.service.port }}
      targetPort: oauth2-proxy
      protocol: TCP
      name: oauth2-proxy
  selector:
    {{- include "sourcebot.oauth2ProxySelectorLabels" . | nindent 4 }}
{{- end }}